In [1]:
# 기존 데이터프레임에서 특정 컬럼을 선택하여 새로운 데이터프레임을 만들기
import pandas as pd

In [2]:
df_main = pd.read_csv('/Users/being/Desktop/[github] workspace/AI/featureSelector/data/c4_general_cafeteria_chuncheon_CC_opened_SS-HJ_addLatiLongti.csv', encoding='utf-8')

In [3]:
# 전처리
# '사업장명'은 'cafeteria_name'로 변경
df_main.rename(columns={'사업장명':'cafeteria_name'}, inplace=True)

# '업태구분명'은 'cafeteria_type_orignal'으로 변경
df_main.rename(columns={'업태구분명':'cafeteria_type_orignal'}, inplace=True)

# 'index_cafeteria'는 int형으로 변경
df_main['index_cafeteria'] = df_main['index_cafeteria'].astype(int)

df_main

,index_cafeteria,인허가일자,영업상태구분코드,소재지전체주소,Latitude,Longitude,cafeteria_name,cafeteria_type_orignal,시설총규모,최종수정시점,시/도,구/군,동/면,상세주소
0,7502,2023-08-16,1,강원특별자치도 춘천시 석사동 654-19,37.859445,127.740166,백돈춘천점,기타,86.13,2023-08-16 14:35:53,강원특별자치도,춘천시,석사동,654-19
1,7519,2023-08-09,1,강원특별자치도 춘천시 석사동 885-3,37.852339,127.745196,야미마라탕,중국식,96.00,2023-08-11 16:34:22,강원특별자치도,춘천시,석사동,885-3
2,7523,2023-08-11,1,강원특별자치도 춘천시 효자동 590-48,37.869167,127.725577,곰소젓갈밥상,한식,87.84,2023-08-11 16:26:26,강원특별자치도,춘천시,효자동,590-48
3,7524,2023-08-11,1,강원특별자치도 춘천시 효자동 652-3,37.875470,127.735500,호앤호,기타,112.00,2023-08-21 16:31:40,강원특별자치도,춘천시,효자동,652-3
4,7526,2023-08-04,1,강원특별자치도 춘천시 효자동 305-46,37.864947,127.734955,넘버25호텔남춘천점,기타,53.04,2023-08-07 8:58:17,강원특별자치도,춘천시,효자동,305-46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1167,12398,2023-09-20,1,강원특별자치도 춘천시 석사동 840-9,37.853174,127.746671,밥의민족,한식,105.00,2023-10-23 15:10:45,강원특별자치도,춘천시,석사동,840-9
1168,10155,2023-03-08,1,강원특별자치도 춘천시 석사동 818-1,37.856496,127.742842,김밥나라봄내초교점,한식,59.69,2023-03-14 17:30:24,강원특별자치도,춘천시,석사동,818-1
1169,10156,2023-03-08,1,강원특별자치도 춘천시 효자동 748-13,37.878113,127.739507,케이크베이크(cake bake),기타,38.00,2023-03-31 10:34:40,강원특별자치도,춘천시,효자동,748-13
1170,10158,2023-03-09,1,강원특별자치도 춘천시 효자동 628-14,37.873420,127.743982,공식술상,기타,138.33,2023-08-31 17:08:39,강원특별자치도,춘천시,효자동,628-14
1171,10162,2022-10-17,1,강원특별자치도 춘천시 효자동 694-11,37.867858,127.728497,스시젠,일식,50.00,2022-10-28 9:44:55,강원특별자치도,춘천시,효자동,694-11

In [4]:
df_manu = pd.read_csv('/Users/being/Desktop/[github] workspace/AI/featureSelector/data/c4_general_cafeteria_chuncheon_CC_opened_SS-HJ_addLatiLongti_menu-price_addedLabel.csv', encoding='utf-8')

In [5]:
df_manu

,index_cafeteria,cafeteria_name,menu_name,menu_price,label
0,7502.0,백돈춘천점,NaN,NaN,NaN
1,7519.0,야미마라탕,꿔바로우소,NaN,중식
2,7519.0,야미마라탕,새우볶음밥,NaN,찜/탕/찌개
3,7519.0,야미마라탕,마라탕,NaN,중식
4,7523.0,곰소젓갈밥상,NaN,NaN,NaN
...,...,...,...,...,...
1881,11278.0,순살만공격춘천점,페퍼로니 피자&치킨 세트,NaN,피자
1882,11278.0,순살만공격춘천점,치파포 V5,NaN,치킨
1883,11282.0,한방전주콩나물국밥효자점,콩나물국밥,"5,500",국밥
1884,11282.0,한방전주콩나물국밥효자점,황태콩나물국밥,"7,500",국밥
1885,11282.0,한방전주콩나물국밥효자점,콩나물비빔밥,"6,500",국밥

In [6]:
# df_manu에서 label열에 결측치가 있는 행을 제거
df_manu_fillter = df_manu.dropna(subset=['label'])
df_manu_fillter

,index_cafeteria,cafeteria_name,menu_name,menu_price,label
1,7519.0,야미마라탕,꿔바로우소,NaN,중식
2,7519.0,야미마라탕,새우볶음밥,NaN,찜/탕/찌개
3,7519.0,야미마라탕,마라탕,NaN,중식
7,7535.0,피시프레시,물회,"12,000",회
8,7535.0,피시프레시,회덮밥,"6,000",국밥
...,...,...,...,...,...
1881,11278.0,순살만공격춘천점,페퍼로니 피자&치킨 세트,NaN,피자
1882,11278.0,순살만공격춘천점,치파포 V5,NaN,치킨
1883,11282.0,한방전주콩나물국밥효자점,콩나물국밥,"5,500",국밥
1884,11282.0,한방전주콩나물국밥효자점,황태콩나물국밥,"7,500",국밥
1885,11282.0,한방전주콩나물국밥효자점,콩나물비빔밥,"6,500",국밥

In [7]:
# groupby를 통해 'index_cafeteria'을 기준으로 'label'을 묶어준다.(,로 구분)
df_label = df_manu_fillter.groupby('index_cafeteria')['label'].apply(','.join).reset_index()
df_label

     index_cafeteria            label
0             7519.0     중식,찜/탕/찌개,중식
1             7535.0          회,국밥,양식
2             7544.0          양식,분식,회
3             7545.0  고기/구이,찜/탕/찌개,양식
4             7550.0       고기/구이,회,중식
..               ...              ...
512          11263.0         양식,중식,국수
513          11264.0      분식,고기/구이,분식
514          11266.0       고기/구이,양식,회
515          11278.0      고기/구이,피자,치킨
516          11282.0         국밥,국밥,국밥

[517 rows x 2 columns]

In [8]:
# df_label의 'label'열의 첫번째 값만 추출하여 리스트로 만들기
label_list = []
for i in df_label['label']:
    label_list.append(i.split(',')[0])
    
df_label['label'] = label_list

In [9]:
df_label

     index_cafeteria  label
0             7519.0     중식
1             7535.0      회
2             7544.0     양식
3             7545.0  고기/구이
4             7550.0  고기/구이
..               ...    ...
512          11263.0     양식
513          11264.0     분식
514          11266.0  고기/구이
515          11278.0  고기/구이
516          11282.0     국밥

[517 rows x 2 columns]

In [10]:
# cafeteria_name를 기준으로 합치기 how는 합집합
df = pd.merge(df_main, df_label, on='index_cafeteria', how='outer')
df

,index_cafeteria,인허가일자,영업상태구분코드,소재지전체주소,Latitude,Longitude,cafeteria_name,cafeteria_type_orignal,시설총규모,최종수정시점,시/도,구/군,동/면,상세주소,label
0,7502,2023-08-16,1,강원특별자치도 춘천시 석사동 654-19,37.859445,127.740166,백돈춘천점,기타,86.13,2023-08-16 14:35:53,강원특별자치도,춘천시,석사동,654-19,NaN
1,7519,2023-08-09,1,강원특별자치도 춘천시 석사동 885-3,37.852339,127.745196,야미마라탕,중국식,96.00,2023-08-11 16:34:22,강원특별자치도,춘천시,석사동,885-3,중식
2,7523,2023-08-11,1,강원특별자치도 춘천시 효자동 590-48,37.869167,127.725577,곰소젓갈밥상,한식,87.84,2023-08-11 16:26:26,강원특별자치도,춘천시,효자동,590-48,NaN
3,7524,2023-08-11,1,강원특별자치도 춘천시 효자동 652-3,37.875470,127.735500,호앤호,기타,112.00,2023-08-21 16:31:40,강원특별자치도,춘천시,효자동,652-3,NaN
4,7526,2023-08-04,1,강원특별자치도 춘천시 효자동 305-46,37.864947,127.734955,넘버25호텔남춘천점,기타,53.04,2023-08-07 8:58:17,강원특별자치도,춘천시,효자동,305-46,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1167,12398,2023-09-20,1,강원특별자치도 춘천시 석사동 840-9,37.853174,127.746671,밥의민족,한식,105.00,2023-10-23 15:10:45,강원특별자치도,춘천시,석사동,840-9,NaN
1168,10155,2023-03-08,1,강원특별자치도 춘천시 석사동 818-1,37.856496,127.742842,김밥나라봄내초교점,한식,59.69,2023-03-14 17:30:24,강원특별자치도,춘천시,석사동,818-1,NaN
1169,10156,2023-03-08,1,강원특별자치도 춘천시 효자동 748-13,37.878113,127.739507,케이크베이크(cake bake),기타,38.00,2023-03-31 10:34:40,강원특별자치도,춘천시,효자동,748-13,NaN
1170,10158,2023-03-09,1,강원특별자치도 춘천시 효자동 628-14,37.873420,127.743982,공식술상,기타,138.33,2023-08-31 17:08:39,강원특별자치도,춘천시,효자동,628-14,NaN
1171,10162,2022-10-17,1,강원특별자치도 춘천시 효자동 694-11,37.867858,127.728497,스시젠,일식,50.00,2022-10-28 9:44:55,강원특별자치도,춘천시,효자동,694-11,NaN

In [11]:
df['label'].value_counts()

label
양식        122
고기/구이     119
치킨         52
회          45
중식         43
국수         31
분식         28
국밥         27
백반         19
찜/탕/찌개     11
버거          8
피자          6
돈까스         4
일식          1
족발/보쌈       1
Name: count, dtype: int64

In [12]:
# label의 널값 분포
df['label'].isnull().sum()

655

In [14]:
# label의 널값을 '기타'로 채우기
df['label'].fillna('기타', inplace=True)
df

,index_cafeteria,인허가일자,영업상태구분코드,소재지전체주소,Latitude,Longitude,cafeteria_name,cafeteria_type_orignal,시설총규모,최종수정시점,시/도,구/군,동/면,상세주소,label
0,7502,2023-08-16,1,강원특별자치도 춘천시 석사동 654-19,37.859445,127.740166,백돈춘천점,기타,86.13,2023-08-16 14:35:53,강원특별자치도,춘천시,석사동,654-19,기타
1,7519,2023-08-09,1,강원특별자치도 춘천시 석사동 885-3,37.852339,127.745196,야미마라탕,중국식,96.00,2023-08-11 16:34:22,강원특별자치도,춘천시,석사동,885-3,중식
2,7523,2023-08-11,1,강원특별자치도 춘천시 효자동 590-48,37.869167,127.725577,곰소젓갈밥상,한식,87.84,2023-08-11 16:26:26,강원특별자치도,춘천시,효자동,590-48,기타
3,7524,2023-08-11,1,강원특별자치도 춘천시 효자동 652-3,37.875470,127.735500,호앤호,기타,112.00,2023-08-21 16:31:40,강원특별자치도,춘천시,효자동,652-3,기타
4,7526,2023-08-04,1,강원특별자치도 춘천시 효자동 305-46,37.864947,127.734955,넘버25호텔남춘천점,기타,53.04,2023-08-07 8:58:17,강원특별자치도,춘천시,효자동,305-46,기타
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1167,12398,2023-09-20,1,강원특별자치도 춘천시 석사동 840-9,37.853174,127.746671,밥의민족,한식,105.00,2023-10-23 15:10:45,강원특별자치도,춘천시,석사동,840-9,기타
1168,10155,2023-03-08,1,강원특별자치도 춘천시 석사동 818-1,37.856496,127.742842,김밥나라봄내초교점,한식,59.69,2023-03-14 17:30:24,강원특별자치도,춘천시,석사동,818-1,기타
1169,10156,2023-03-08,1,강원특별자치도 춘천시 효자동 748-13,37.878113,127.739507,케이크베이크(cake bake),기타,38.00,2023-03-31 10:34:40,강원특별자치도,춘천시,효자동,748-13,기타
1170,10158,2023-03-09,1,강원특별자치도 춘천시 효자동 628-14,37.873420,127.743982,공식술상,기타,138.33,2023-08-31 17:08:39,강원특별자치도,춘천시,효자동,628-14,기타
1171,10162,2022-10-17,1,강원특별자치도 춘천시 효자동 694-11,37.867858,127.728497,스시젠,일식,50.00,2022-10-28 9:44:55,강원특별자치도,춘천시,효자동,694-11,기타

In [18]:
# 저장하기 to_csv
df.to_csv('/Users/being/Desktop/[github] workspace/AI/featureSelector/data/c4_general_cafeteria_chuncheon_CC_opened_SS-HJ_addLatiLongti_addedLabel_addedLabel.csv', encoding='utf-8', index=True)